name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
        with:
          heroku_api_key: ${{secrets.HRKU-721bdcdb-6543-4cf2-b3e0-6849591fa470}}
          heroku_app_name: "e-coffee" #Must be unique in Heroku
          heroku_email: "lauren.elisiario@proton.me"